### ISSUE TITLE
Tested successfully

### ISSUE THREAD

**Issue by Mahyulan** [xisonc/hcaptcha-for-elementor-forms#1]
Hello,

Thanks for making this plugin.
Crazy that Elementor refuses to implement even though many people asked for this feature.
I just tested your plugin on one of my sites and it works fine.
Hopefully you can fix the error message that you mention, than it would even be perfect.
Thank again.

**Comment by xisonc** [comment]
Note the error message has been fixed by @paulcpn, and committed to the main branch.
